apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      name: api-gateway
      labels:
        app: api-gateway
    spec:
      containers:
        - name: gateway
          image: public.ecr.aws/v0c3x7n3/qnac/gateway:latest
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
      