apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  labels:
    app: search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      name: search
      labels:
        app: search
    spec:
      containers:
        - name: search
          image: public.ecr.aws/v0c3x7n3/qnac/search-service:latest
      restartPolicy: Always
      