apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      name: notification-service
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification
          image: us-central1-docker.pkg.dev/mimetic-codex-460815-g8/smr-repo/notificationservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
              protocol: TCP
          volumeMounts:
            - name: firebase-sa-key-volume
              mountPath: "/secrets/firebase"
              readOnly: true
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/firebase/smr-back-firebase-adminsdk-fbsvc-a6a2c91210.json
          resources:
            requests:
              cpu: "100m"
      restartPolicy: Always
      volumes:
        - name: firebase-sa-key-volume
          secret:
            secretName: smr-back-firebase-secret
            items:
              - key: smr-back-firebase-adminsdk-fbsvc-a6a2c91210.json
                path: smr-back-firebase-adminsdk-fbsvc-a6a2c91210.json
