apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"80":"cloud-gateway-backendconfig"}}'
spec:
  selector:
    app: cloud-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: ClusterIP
  