apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway
  labels:
    app: cloud-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-gateway
  template:
    metadata:
      name: cloud-gateway
      labels:
        app: cloud-gateway
    spec:
      containers:
        - name: gateway
          image: us-central1-docker.pkg.dev/mimetic-codex-460815-g8/smr-repo/cloudgateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
      restartPolicy: Always
      