apiVersion: apps/v1
kind: Deployment
metadata:
  name: qna
  labels:
    app: qna
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qna
  template:
    metadata:
      name: qna
      labels:
        app: qna
    spec:
      containers:
        - name: qna
          image: public.ecr.aws/v0c3x7n3/qnac/qna-service:latest
          imagePullPolicy: Always
      restartPolicy: Always
      