apiVersion: v1
kind: Service
metadata:
  name: user-action-service
spec:
  selector:
    app: user-action-service
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
  type: ClusterIP
  