pipeline {
    agent any

    stages {
        stage('Update kubeconfig') {
            steps {
                withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'e046f63b-a53a-4c53-bbc5-cbcd1c97c379', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                    sh "aws eks update-kubeconfig --name qnac-k8s"
                }
            }
        }
        stage('Apply to AWS EKS') {
            steps {
                withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'e046f63b-a53a-4c53-bbc5-cbcd1c97c379', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                    dir('qnac-consul') {
                        sh "kubectl --namespace=default apply -f qnac-consul-deployment.yaml"
                        sh "kubectl --namespace=default apply -f qnac-consul-service.yaml"
                    }
                    dir('qnac-gateway') {
                        sh "kubectl --namespace=default apply -f qnac-gateway-deployment.yaml"
                        sh "kubectl --namespace=default apply -f qnac-gateway-service.yaml"
                    }
                    dir('qnac-qna') {
                        sh "kubectl --namespace=default apply -f qnac-qna-deployment.yaml"
                    }
                    dir('qnac-search') {
                        sh "kubectl --namespace=default apply -f qnac-search-deployment.yaml"
                    }
                    dir('qnac-event') {
                        sh "kubectl --namespace=default apply -f qnac-event-deployment.yaml"
                    }
                    dir('qnac-vote') {
                        sh "kubectl --namespace=default apply -f qnac-vote-deployment.yaml"
                    }
                }
            }
        }
        stage('Get API Gateway Endpoint') {
            steps {
                withCredentials([aws(accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'e046f63b-a53a-4c53-bbc5-cbcd1c97c379', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
                    sh "kubectl get svc api-gateway"
                }
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}
