apiVersion: v1
kind: Service
metadata:
  name: consul
spec:
  selector:
    app: consul
  ports:
    - name: default
      protocol: TCP
      port: 8500
      targetPort: 8500
    - name: default-udp
      protocol: UDP
      port: 8600
      targetPort: 8600
  type: ClusterIP
  