apiVersion: apps/v1
kind: Deployment
metadata:
  name: event
  labels:
    app: event
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event
  template:
    metadata:
      name: event
      labels:
        app: event
    spec:
      containers:
        - name: event
          image: public.ecr.aws/v0c3x7n3/qnac/event-service:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "50m"
      restartPolicy: Always
      